### ISSUE TITLE
[Intro to iOS] Week 1 Assignment: Review my app

### ISSUE THREAD

**Issue by marcel** [marcel/RottenTomatoes#1]
/cc @codepath

**Comment by codepathreview** [comment]
:+1: nice work. The point of this homework was to explore a simple example of a full MVC application with a RESTful API.

Here's a checklist of things that I'm looking for in this project. You should review the checklist, and make any changes to your project, if necessary.
- Code styling: check out the [Ray Wenderlich Swift Style Guide](https://github.com/raywenderlich/swift-style-guide) and the [Github Swift Style Guide](https://github.com/github/swift-style-guide)
- Review the properties and methods that you've made public. Your classes should reveal a minimum interface and only expose things that must be used by other classes.
- Consider using SwiftyJSON for easier deserialization of the JSON response.
- When creating a custom cell, make sure never to use imageView, titleLabel, or subtitleLabel.  Those are already used by UITableViewCell and using them in your custom cell will cause subtle things to happen such as image views not loading until you click on the cell.
- The images should be downloaded asynchronously. One way to do that was to use AFNetworking, installed via CocoaPods.
- Observe the UIContentMode of the UIImageView. By default, it will stretch the image to match your dimensions, which is probably not what you want.
- Next week, we'll cover how to use Auto Layout constraints to implement dynamic height rows and adjust to synopsis of different length.

In general, you should challenge yourself to create visually polished applications. That's where you'll find all the rough edges of the iOS framework and earn the next level of mastery.

-- dirk

**Comment by codepathreview** [comment]
:+1: nice work. The point of this homework was to explore a simple example of a full MVC application with a RESTful API. For each point in the homework feedback checklist, I'll either confirm that you're on the right track with the implementation, or I'll provide some feedback:
- great you are using a .gitignore file
- Nice code styling. Check out these Swift style guides:
  - [Ray Wenderlich Swift Style Guide](https://github.com/raywenderlich/swift-style-guide)
  - [Github Swift Style Guide](https://github.com/github/swift-style-guide)
- Nice work with the access controls in the classes. You should always try to minimize the number of properties and functions that are public or internal.
- Nice work implementing the Movie model.
- Nice work with the custom Movie cell and encapsulating it so that it can configure itself based on the `movie` instance.
- Nice work loading the images asynchronously.
- Nice work setting up the proper modes for the images so that they are not stretched.
- Nice work implementing the error message on network failure.
- Nice job on the client
- kudos for the extra filtering
- looked great on my iPhone 6s

In general, you should challenge yourself to create visually polished applications. That's where you'll find all the rough edges of the iOS framework and earn the next level of mastery.

-- dirk
